SET FOREIGN_KEY_CHECKS=0;
DELETE FROM reconciliation_allocations;
DELETE FROM late_fee_ledger;
DELETE FROM contract_fee_items;
DELETE FROM contract_initial_payments;
DELETE FROM factory_repayments;
DELETE FROM repayments;
DELETE FROM waivers;
DELETE FROM invoice_requests;
DELETE FROM return_inspections;
DELETE FROM ownership_transfers;
DELETE FROM vehicle_rebates;
DELETE FROM approval_flows;
DELETE FROM attachments;
DELETE FROM daily_job_runs;
DELETE FROM urge_records;
DELETE FROM lock_requests;
DELETE FROM customer_prepayments;
DELETE FROM receivables;
DELETE FROM customer_blacklist;
DELETE FROM customers;
DELETE FROM sales_orders;
DELETE FROM contracts;
DELETE FROM vehicles;
DELETE FROM audit_logs;
SET FOREIGN_KEY_CHECKS=1;
SELECT 'ALL_CLEAR_SUCCESS' AS result;
